using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace ZeroAlloc.Serialisation.Generator.Tests;

// Locks down the exact emitted source text for six representative
// (format × shape) combinations. Any accidental drift in the generator
// output — a new `#nullable` directive, spacing change, different using
// order — fails these tests loudly. When intentional, update the
// corresponding Expected_* constant to match the new emission.
//
// The comparison normalises line endings (CRLF → LF) so the tests are
// stable across platforms / git autocrlf settings.
public sealed class SerializerEmissionSnapshotTests
{
    private const string TrimSuppress =
        "    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"T is a closed concrete type annotated [ZeroAllocSerializable]; the generator only emits bindings the caller already references.\")]";

    private const string AotSuppress =
        "    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\", Justification = \"T is a closed concrete type annotated [ZeroAllocSerializable]; no open generics or runtime code generation is introduced.\")]";

    // ── MemoryPack ───────────────────────────────────────────────────────────

    private static readonly string Expected_MemoryPack_PlainClass = $$"""
        // <auto-generated/>
        // NOTE: This generated class is internal to the assembly where [ZeroAllocSerializable] is applied.
        // It is not accessible from other assemblies. This is by design — apply [ZeroAllocSerializable]
        // to types in the assembly that will use the serializer.
        #nullable enable
        using System.Buffers;
        using ZeroAlloc.Serialisation;

        namespace Demo;

        internal sealed class MpBasicSerializer : ISerializer<Demo.MpBasic>
        {
        {{TrimSuppress}}
        {{AotSuppress}}
            public void Serialize(IBufferWriter<byte> writer, Demo.MpBasic value)
            {
                global::MemoryPack.MemoryPackSerializer.Serialize(writer, value);
            }

        {{TrimSuppress}}
        {{AotSuppress}}
            public Demo.MpBasic? Deserialize(ReadOnlySpan<byte> buffer)
            {
                if (buffer.IsEmpty) return default;
                return global::MemoryPack.MemoryPackSerializer.Deserialize<Demo.MpBasic>(buffer);
            }
        }
        """;

    private static readonly string Expected_MemoryPack_Record = $$"""
        // <auto-generated/>
        // NOTE: This generated class is internal to the assembly where [ZeroAllocSerializable] is applied.
        // It is not accessible from other assemblies. This is by design — apply [ZeroAllocSerializable]
        // to types in the assembly that will use the serializer.
        #nullable enable
        using System.Buffers;
        using ZeroAlloc.Serialisation;

        namespace Demo;

        internal sealed class MpRecSerializer : ISerializer<Demo.MpRec>
        {
        {{TrimSuppress}}
        {{AotSuppress}}
            public void Serialize(IBufferWriter<byte> writer, Demo.MpRec value)
            {
                global::MemoryPack.MemoryPackSerializer.Serialize(writer, value);
            }

        {{TrimSuppress}}
        {{AotSuppress}}
            public Demo.MpRec? Deserialize(ReadOnlySpan<byte> buffer)
            {
                if (buffer.IsEmpty) return default;
                return global::MemoryPack.MemoryPackSerializer.Deserialize<Demo.MpRec>(buffer);
            }
        }
        """;

    // ── MessagePack ──────────────────────────────────────────────────────────

    private static readonly string Expected_MessagePack_PlainClass = $$"""
        // <auto-generated/>
        // NOTE: This generated class is internal to the assembly where [ZeroAllocSerializable] is applied.
        // It is not accessible from other assemblies. This is by design — apply [ZeroAllocSerializable]
        // to types in the assembly that will use the serializer.
        #nullable enable
        using System.Buffers;
        using ZeroAlloc.Serialisation;

        namespace Demo;

        internal sealed class MsgpBasicSerializer : ISerializer<Demo.MsgpBasic>
        {
        {{TrimSuppress}}
        {{AotSuppress}}
            public void Serialize(IBufferWriter<byte> writer, Demo.MsgpBasic value)
            {
                global::MessagePack.MessagePackSerializer.Serialize(writer, value);
            }

        {{TrimSuppress}}
        {{AotSuppress}}
            public Demo.MsgpBasic? Deserialize(ReadOnlySpan<byte> buffer)
            {
                if (buffer.IsEmpty) return default;
                // MessagePack 3.x has no Deserialize(ReadOnlySpan<byte>) overload — it requires ReadOnlySequence<byte>.
            // Converting from ReadOnlySpan<byte> requires a buffer copy; this allocation is unavoidable with this API.
            return global::MessagePack.MessagePackSerializer.Deserialize<Demo.MsgpBasic>(new global::System.Buffers.ReadOnlySequence<byte>(buffer.ToArray()));
            }
        }
        """;

    private static readonly string Expected_MessagePack_Record = $$"""
        // <auto-generated/>
        // NOTE: This generated class is internal to the assembly where [ZeroAllocSerializable] is applied.
        // It is not accessible from other assemblies. This is by design — apply [ZeroAllocSerializable]
        // to types in the assembly that will use the serializer.
        #nullable enable
        using System.Buffers;
        using ZeroAlloc.Serialisation;

        namespace Demo;

        internal sealed class MsgpRecSerializer : ISerializer<Demo.MsgpRec>
        {
        {{TrimSuppress}}
        {{AotSuppress}}
            public void Serialize(IBufferWriter<byte> writer, Demo.MsgpRec value)
            {
                global::MessagePack.MessagePackSerializer.Serialize(writer, value);
            }

        {{TrimSuppress}}
        {{AotSuppress}}
            public Demo.MsgpRec? Deserialize(ReadOnlySpan<byte> buffer)
            {
                if (buffer.IsEmpty) return default;
                // MessagePack 3.x has no Deserialize(ReadOnlySpan<byte>) overload — it requires ReadOnlySequence<byte>.
            // Converting from ReadOnlySpan<byte> requires a buffer copy; this allocation is unavoidable with this API.
            return global::MessagePack.MessagePackSerializer.Deserialize<Demo.MsgpRec>(new global::System.Buffers.ReadOnlySequence<byte>(buffer.ToArray()));
            }
        }
        """;

    // ── SystemTextJson ───────────────────────────────────────────────────────

    private static readonly string Expected_SystemTextJson_PlainClass = $$"""
        // <auto-generated/>
        // NOTE: This generated class is internal to the assembly where [ZeroAllocSerializable] is applied.
        // It is not accessible from other assemblies. This is by design — apply [ZeroAllocSerializable]
        // to types in the assembly that will use the serializer.
        #nullable enable
        using System.Buffers;
        using ZeroAlloc.Serialisation;

        namespace Demo;

        internal sealed class StjBasicSerializer : ISerializer<Demo.StjBasic>
        {
        {{TrimSuppress}}
        {{AotSuppress}}
            public void Serialize(IBufferWriter<byte> writer, Demo.StjBasic value)
            {
                using var _jw = new global::System.Text.Json.Utf8JsonWriter(writer);
                global::System.Text.Json.JsonSerializer.Serialize(_jw, value);
            }

        {{TrimSuppress}}
        {{AotSuppress}}
            public Demo.StjBasic? Deserialize(ReadOnlySpan<byte> buffer)
            {
                if (buffer.IsEmpty) return default;
                return global::System.Text.Json.JsonSerializer.Deserialize<Demo.StjBasic>(buffer);
            }
        }
        """;

    private static readonly string Expected_SystemTextJson_Record = $$"""
        // <auto-generated/>
        // NOTE: This generated class is internal to the assembly where [ZeroAllocSerializable] is applied.
        // It is not accessible from other assemblies. This is by design — apply [ZeroAllocSerializable]
        // to types in the assembly that will use the serializer.
        #nullable enable
        using System.Buffers;
        using ZeroAlloc.Serialisation;

        namespace Demo;

        internal sealed class StjRecSerializer : ISerializer<Demo.StjRec>
        {
        {{TrimSuppress}}
        {{AotSuppress}}
            public void Serialize(IBufferWriter<byte> writer, Demo.StjRec value)
            {
                using var _jw = new global::System.Text.Json.Utf8JsonWriter(writer);
                global::System.Text.Json.JsonSerializer.Serialize(_jw, value);
            }

        {{TrimSuppress}}
        {{AotSuppress}}
            public Demo.StjRec? Deserialize(ReadOnlySpan<byte> buffer)
            {
                if (buffer.IsEmpty) return default;
                return global::System.Text.Json.JsonSerializer.Deserialize<Demo.StjRec>(buffer);
            }
        }
        """;

    // ── Tests ────────────────────────────────────────────────────────────────

    [Fact]
    public void MemoryPack_PlainClass_EmitsExactSource()
    {
        const string source = """
            using ZeroAlloc.Serialisation;
            namespace Demo;
            [ZeroAllocSerializable(SerializationFormat.MemoryPack)]
            public sealed class MpBasic { public string V { get; set; } = ""; }
            """;

        var actual = EmitSerializer(source, "MpBasicSerializer.g.cs");
        AssertSnapshot(Expected_MemoryPack_PlainClass, actual);
    }

    [Fact]
    public void MemoryPack_Record_EmitsExactSource()
    {
        const string source = """
            using ZeroAlloc.Serialisation;
            namespace Demo;
            [ZeroAllocSerializable(SerializationFormat.MemoryPack)]
            public sealed record MpRec(string V);
            """;

        var actual = EmitSerializer(source, "MpRecSerializer.g.cs");
        AssertSnapshot(Expected_MemoryPack_Record, actual);
    }

    [Fact]
    public void MessagePack_PlainClass_EmitsExactSource()
    {
        const string source = """
            using ZeroAlloc.Serialisation;
            namespace Demo;
            [ZeroAllocSerializable(SerializationFormat.MessagePack)]
            public sealed class MsgpBasic { public string V { get; set; } = ""; }
            """;

        var actual = EmitSerializer(source, "MsgpBasicSerializer.g.cs");
        AssertSnapshot(Expected_MessagePack_PlainClass, actual);
    }

    [Fact]
    public void MessagePack_Record_EmitsExactSource()
    {
        const string source = """
            using ZeroAlloc.Serialisation;
            namespace Demo;
            [ZeroAllocSerializable(SerializationFormat.MessagePack)]
            public sealed record MsgpRec(string V);
            """;

        var actual = EmitSerializer(source, "MsgpRecSerializer.g.cs");
        AssertSnapshot(Expected_MessagePack_Record, actual);
    }

    [Fact]
    public void SystemTextJson_PlainClass_EmitsExactSource()
    {
        const string source = """
            using ZeroAlloc.Serialisation;
            namespace Demo;
            [ZeroAllocSerializable(SerializationFormat.SystemTextJson)]
            public sealed class StjBasic { public string V { get; set; } = ""; }
            """;

        var actual = EmitSerializer(source, "StjBasicSerializer.g.cs");
        AssertSnapshot(Expected_SystemTextJson_PlainClass, actual);
    }

    [Fact]
    public void SystemTextJson_Record_EmitsExactSource()
    {
        const string source = """
            using ZeroAlloc.Serialisation;
            namespace Demo;
            [ZeroAllocSerializable(SerializationFormat.SystemTextJson)]
            public sealed record StjRec(string V);
            """;

        var actual = EmitSerializer(source, "StjRecSerializer.g.cs");
        AssertSnapshot(Expected_SystemTextJson_Record, actual);
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private static string EmitSerializer(string source, string hintName)
    {
        var tree = CSharpSyntaxTree.ParseText(source);
        var zeroAllocRef = MetadataReference.CreateFromFile(
            typeof(ZeroAlloc.Serialisation.ZeroAllocSerializableAttribute).Assembly.Location);
        var refs = new System.Collections.Generic.List<MetadataReference>(
            Basic.Reference.Assemblies.Net100.References.All) { zeroAllocRef };
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { tree },
            refs,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        var driver = CSharpGeneratorDriver.Create(new SerializerGenerator())
            .RunGenerators(compilation);
        var result = driver.GetRunResult();
        var file = result.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.Contains(hintName, StringComparison.Ordinal));
        Assert.NotNull(file);
        return file!.GetText().ToString();
    }

    private static void AssertSnapshot(string expected, string actual)
    {
        var e = Normalise(expected);
        var a = Normalise(actual);
        Assert.Equal(e, a);
    }

    // Normalise line endings so the snapshot survives CRLF/LF differences
    // across platforms and git autocrlf configurations.
    private static string Normalise(string s)
        => s.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace("\r",   "\n", StringComparison.Ordinal)
            .Trim();
}
