using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace ZeroAlloc.Serialisation.Generator.Tests;

/// <summary>
/// Exact output for the <c>[ValueObject]</c> emitters. Struct output predates class and nested
/// support and must not change; nested and reference-type output is pinned so its layout does
/// not drift.
/// </summary>
public sealed class ValueObjectShapeEmissionTests
{
    private const string ValueObjectStub = """
        namespace ZeroAlloc.ValueObjects
        {
            [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
            public sealed class ValueObjectAttribute : System.Attribute { }
        }
        """;

    private const string TopLevelStruct = """
        using ZeroAlloc.ValueObjects;
        namespace Demo.Inner;

        [ValueObject]
        public readonly partial struct CustomerId
        {
            public int Value { get; }
            public CustomerId(int value) => Value = value;
        }
        """;

    private const string Nested = """
        using ZeroAlloc.ValueObjects;
        namespace Demo;

        public partial class Outer
        {
            public readonly partial struct Middle
            {
                [ValueObject]
                public sealed partial record DeepName(string Value);
            }

            [ValueObject]
            private sealed partial class PrivateId
            {
                public int Value { get; }
                public PrivateId(int value) => Value = value;
            }
        }
        """;

    [Fact]
    public void TopLevelStruct_SystemTextJsonConverter_IsUnchanged()
    {
        var text = Generated(TopLevelStruct, "Demo.Inner.CustomerIdSystemTextJsonConverter.g.cs");

        AssertSameText("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Text.Json;
            using System.Text.Json.Serialization;

            namespace Demo.Inner;

            [JsonConverter(typeof(CustomerIdSystemTextJsonConverter))]
            public readonly partial struct CustomerId
            {
            }

            internal sealed class CustomerIdSystemTextJsonConverter : JsonConverter<CustomerId>
            {
                public override CustomerId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
                    => new CustomerId(reader.GetInt32());

                public override void Write(Utf8JsonWriter writer, CustomerId value, JsonSerializerOptions options)
                    => writer.WriteNumberValue(value.Value);
            }

            """, text);
    }

    [Fact]
    public void TopLevelStruct_MessagePackFormatter_IsUnchanged()
    {
        var text = Generated(TopLevelStruct, "Demo.Inner.CustomerIdMessagePackFormatter.g.cs");

        AssertSameText("""
            // <auto-generated/>
            #nullable enable

            using MessagePack;
            using MessagePack.Formatters;

            namespace Demo.Inner;

            [MessagePackFormatter(typeof(CustomerIdMessagePackFormatter))]
            public readonly partial struct CustomerId
            {
            }

            internal sealed class CustomerIdMessagePackFormatter : IMessagePackFormatter<CustomerId>
            {
                public void Serialize(ref MessagePackWriter writer, CustomerId value, MessagePackSerializerOptions options)
                    => writer.Write(value.Value);

                public CustomerId Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
                    => new CustomerId(reader.ReadInt32());
            }

            """, text);
    }

    [Fact]
    public void TopLevelStruct_MemoryPackFormatter_IsUnchanged()
    {
        var text = Generated(TopLevelStruct, "Demo.Inner.CustomerIdMemoryPackFormatter.g.cs");

        AssertSameText("""
            // <auto-generated/>
            #nullable enable

            using System.Runtime.CompilerServices;
            using MemoryPack;

            namespace Demo.Inner;

            internal static class CustomerIdMemoryPackFormatterRegistrar
            {
                [ModuleInitializer]
                internal static void Register()
                {
                    if (!MemoryPackFormatterProvider.IsRegistered<CustomerId>())
                    {
                        MemoryPackFormatterProvider.Register<CustomerId>(new CustomerIdMemoryPackFormatter());
                    }
                }
            }

            internal sealed class CustomerIdMemoryPackFormatter : MemoryPackFormatter<CustomerId>
            {
                public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, scoped ref CustomerId value)
                    => writer.WriteValue<int>(value.Value);

                public override void Deserialize(ref MemoryPackReader reader, scoped ref CustomerId value)
                    => value = new CustomerId(reader.ReadValue<int>()!);
            }

            """, text);
    }

    [Fact]
    public void NestedRecordClass_IsDeclaredInsideItsContainingTypes()
    {
        var text = Generated(Nested, "Demo.Outer.Middle.DeepNameMessagePackFormatter.g.cs");

        AssertSameText("""
            // <auto-generated/>
            #nullable enable

            using MessagePack;
            using MessagePack.Formatters;

            namespace Demo;

            public partial class Outer
            {
                public readonly partial struct Middle
                {
                    [MessagePackFormatter(typeof(DeepNameMessagePackFormatter))]
                    public partial record DeepName
                    {
                    }

                    internal sealed class DeepNameMessagePackFormatter : IMessagePackFormatter<DeepName?>
                    {
                        public void Serialize(ref MessagePackWriter writer, DeepName? value, MessagePackSerializerOptions options)
                        {
                            if (value is null)
                            {
                                writer.WriteNil();
                                return;
                            }

                            writer.Write(value.Value);
                        }

                        public DeepName? Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
                            => reader.TryReadNil() ? null : new DeepName(reader.ReadString()!);
                    }
                }
            }

            """, text);
    }

    [Fact]
    public void PrivateNestedClass_GetsPrivateSiblings_AndStaysOutOfTheRegistrars()
    {
        var result = RunGenerator(Nested);

        var converter = Text(result, "Demo.Outer.PrivateIdSystemTextJsonConverter.g.cs");
        Assert.Contains("private partial class PrivateId", converter, StringComparison.Ordinal);
        Assert.Contains("private sealed class PrivateIdSystemTextJsonConverter : JsonConverter<PrivateId>", converter, StringComparison.Ordinal);

        // The registrars live at namespace level, where a private nested type cannot be named;
        // the attribute on the partial declaration still serves it.
        foreach (var hint in new[]
                 {
                     "ValueObjectJsonConvertersExtensions.g.cs",
                     "ValueObjectJsonTypeInfoResolver.g.cs",
                     "ValueObjectMessagePackResolverExtensions.g.cs",
                 })
        {
            var registrar = Text(result, hint);
            Assert.DoesNotContain("PrivateId", registrar, StringComparison.Ordinal);
            Assert.Contains("global::Demo.Outer.Middle.DeepName", registrar, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void ReferenceType_MessagePackResolver_HasNoNullableArm()
    {
        var text = Text(RunGenerator(Nested), "ValueObjectMessagePackResolverExtensions.g.cs");

        Assert.Contains("return new global::Demo.Outer.Middle.DeepNameMessagePackFormatter();", text, StringComparison.Ordinal);
        Assert.DoesNotContain("Nullable<global::Demo.Outer.Middle.DeepName>", text, StringComparison.Ordinal);
    }

    [Fact]
    public void NestedOutput_HasNoTrailingWhitespace()
    {
        var result = RunGenerator(Nested);

        foreach (var source in result.GeneratedSources)
        {
            var lines = source.SourceText.ToString().Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
            Assert.DoesNotContain(lines, static l => l.Length > 0 && char.IsWhiteSpace(l[^1]));
        }
    }

    // The templates carry the line endings of the generator's source file, which differ between
    // a Windows checkout and CI, so compare with the line endings normalised.
    private static void AssertSameText(string expected, string actual) =>
        Assert.Equal(
            expected.Replace("\r\n", "\n", StringComparison.Ordinal),
            actual.Replace("\r\n", "\n", StringComparison.Ordinal));

    private static string Generated(string source, string hintName) => Text(RunGenerator(source), hintName);

    private static string Text(GeneratorRunResult result, string hintName) =>
        result.GeneratedSources.Single(s => string.Equals(s.HintName, hintName, StringComparison.Ordinal))
            .SourceText.ToString();

    private static GeneratorRunResult RunGenerator(string source)
    {
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            [CSharpSyntaxTree.ParseText(source), CSharpSyntaxTree.ParseText(ValueObjectStub)],
            [
                .. Basic.Reference.Assemblies.Net100.References.All,
                MetadataReference.CreateFromFile(typeof(ZeroAlloc.Serialisation.SystemTextJson.SystemTextJsonSerializer<int>).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(ZeroAlloc.Serialisation.MessagePack.MessagePackSerializer<int>).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(ZeroAlloc.Serialisation.MemoryPack.MemoryPackSerializer<int>).Assembly.Location),
            ],
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var result = CSharpGeneratorDriver.Create(new SerializerGenerator())
            .RunGenerators(compilation)
            .GetRunResult()
            .Results[0];
        Assert.Null(result.Exception);
        return result;
    }
}
