using Microsoft.CodeAnalysis;
using ZeroAlloc.Serialisation.Generator.Models;

namespace ZeroAlloc.Serialisation.Generator;

internal static class DiEmitter
{
    public static void Emit(SourceProductionContext ctx, SerializerModel model, string accessibility)
    {
        var ns = string.IsNullOrEmpty(model.Namespace)
            ? ""
            : $"namespace {model.Namespace};\n\n";

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;
            using ZeroAlloc.Serialisation;

            {{ns}}{{accessibility}} static partial class SerializerServiceCollectionExtensions
            {
                public static IServiceCollection Add{{model.TypeName}}Serializer(
                    this IServiceCollection services)
                {
                    services.TryAddSingleton<ISerializer<{{model.TypeRef}}>, {{model.TypeName}}Serializer>();
                    return services;
                }
            }
            """;

        // The hint name keeps same-named types in different namespaces, and every closed
        // construction of a generic type, apart; see ModelExtractor.HintNameOf.
        ctx.AddSource($"{model.HintName}SerializerExtensions.g.cs", source);
    }
}
