using Microsoft.CodeAnalysis;
using ZeroAlloc.Serialisation.Generator.Models;

namespace ZeroAlloc.Serialisation.Generator;

internal static class DiEmitter
{
    public static void Emit(SourceProductionContext ctx, SerializerModel model)
    {
        var ns = string.IsNullOrEmpty(model.Namespace)
            ? ""
            : $"namespace {model.Namespace};\n\n";

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;
            using ZeroAlloc.Serialisation;

            {{ns}}public static partial class SerializerServiceCollectionExtensions
            {
                public static IServiceCollection Add{{model.TypeName}}Serializer(
                    this IServiceCollection services)
                {
                    services.TryAddSingleton<ISerializer<{{model.FullTypeName}}>, {{model.TypeName}}Serializer>();
                    return services;
                }
            }
            """;

        ctx.AddSource($"{model.TypeName}SerializerExtensions.g.cs", source);
    }
}
