using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using ZeroAlloc.Serialisation.Generator.Models;

namespace ZeroAlloc.Serialisation.Generator;

internal static class DispatcherEmitter
{
    public static void Emit(SourceProductionContext ctx, ImmutableArray<SerializerModel> models)
    {
        if (models.IsDefaultOrEmpty) return;

        EmitDispatcher(ctx, models);
        EmitDiExtension(ctx);
    }

    private static void EmitDispatcher(SourceProductionContext ctx, ImmutableArray<SerializerModel> models)
    {
        var serializeCases = string.Join(
            "\n            ",
            models.Select(m =>
            {
                var typeRef = $"global::{m.FullTypeName}";
                var serializerRef = string.IsNullOrEmpty(m.Namespace)
                    ? $"global::{m.TypeName}Serializer"
                    : $"global::{m.Namespace}.{m.TypeName}Serializer";
                return $"case {typeRef} __e: new {serializerRef}().Serialize(__writer, __e); break;";
            }));

        var deserializeCases = string.Join(
            "\n        ",
            models.Select(m =>
            {
                var typeRef = $"global::{m.FullTypeName}";
                var serializerRef = string.IsNullOrEmpty(m.Namespace)
                    ? $"global::{m.TypeName}Serializer"
                    : $"global::{m.Namespace}.{m.TypeName}Serializer";
                return $"if (type == typeof({typeRef})) return new {serializerRef}().Deserialize(data.Span);";
            }));

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Buffers;
            using global::ZeroAlloc.Serialisation;

            public sealed partial class SerializerDispatcher : ISerializerDispatcher
            {
                /// <inheritdoc/>
                public ReadOnlyMemory<byte> Serialize(object value, Type type)
                {
                    var __writer = new ArrayBufferWriter<byte>();
                    switch (value)
                    {
                        {{serializeCases}}
                        default:
                            throw new NotSupportedException(
                                $"No serializer registered for {type.FullName}. " +
                                "Ensure the type is annotated with [ZeroAllocSerializable].");
                    }
                    return __writer.WrittenMemory;
                }

                /// <inheritdoc/>
                public object? Deserialize(ReadOnlyMemory<byte> data, Type type)
                {
                    {{deserializeCases}}
                    throw new NotSupportedException(
                        $"No serializer registered for {type.FullName}. " +
                        "Ensure the type is annotated with [ZeroAllocSerializable].");
                }
            }
            """;

        ctx.AddSource("SerializerDispatcher.g.cs", source);
    }

    private static void EmitDiExtension(SourceProductionContext ctx)
    {
        var source = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;
            using global::ZeroAlloc.Serialisation;

            public static partial class SerializerServiceCollectionExtensions
            {
                public static IServiceCollection AddSerializerDispatcher(
                    this IServiceCollection services)
                {
                    services.TryAddSingleton<ISerializerDispatcher, SerializerDispatcher>();
                    return services;
                }
            }
            """;

        ctx.AddSource("SerializerDispatcherExtensions.g.cs", source);
    }
}
