using Microsoft.CodeAnalysis;
using ZeroAlloc.Serialisation.Generator.Models;

namespace ZeroAlloc.Serialisation.Generator;

internal static class SerializerEmitter
{
    public static void Emit(SourceProductionContext ctx, SerializerModel model)
    {
        var serializerCall = model.FormatName switch
        {
            "MemoryPack" =>
                "global::MemoryPack.MemoryPackSerializer.Serialize(writer, value);",
            "MessagePack" =>
                "global::MessagePack.MessagePackSerializer.Serialize(writer, value);",
            "SystemTextJson" =>
                "using var _jw = new global::System.Text.Json.Utf8JsonWriter(writer);\n        global::System.Text.Json.JsonSerializer.Serialize(_jw, value);",
            _ => throw new System.InvalidOperationException(
                $"Unknown format '{model.FormatName}'; a ZASZ002 diagnostic should have suppressed emission. This indicates a generator bug."),
        };

        var deserializeCall = model.FormatName switch
        {
            "MemoryPack" =>
                $"return global::MemoryPack.MemoryPackSerializer.Deserialize<{model.FullTypeName}>(buffer);",
            "MessagePack" =>
                $"// MessagePack 3.x has no Deserialize(ReadOnlySpan<byte>) overload — it requires ReadOnlySequence<byte>.\n    // Converting from ReadOnlySpan<byte> requires a buffer copy; this allocation is unavoidable with this API.\n    return global::MessagePack.MessagePackSerializer.Deserialize<{model.FullTypeName}>(new global::System.Buffers.ReadOnlySequence<byte>(buffer.ToArray()));",
            "SystemTextJson" =>
                $"return global::System.Text.Json.JsonSerializer.Deserialize<{model.FullTypeName}>(buffer);",
            _ => throw new System.InvalidOperationException(
                $"Unknown format '{model.FormatName}'; a ZASZ002 diagnostic should have suppressed emission. This indicates a generator bug."),
        };

        var ns = string.IsNullOrEmpty(model.Namespace)
            ? ""
            : $"namespace {model.Namespace};\n\n";

        const string suppressAttrs =
            "    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"T is a closed concrete type annotated [ZeroAllocSerializable]; the generator only emits bindings the caller already references.\")]\n" +
            "    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\", Justification = \"T is a closed concrete type annotated [ZeroAllocSerializable]; no open generics or runtime code generation is introduced.\")]";

        var source = $$"""
            // <auto-generated/>
            // NOTE: This generated class is internal to the assembly where [ZeroAllocSerializable] is applied.
            // It is not accessible from other assemblies. This is by design — apply [ZeroAllocSerializable]
            // to types in the assembly that will use the serializer.
            #nullable enable
            using System.Buffers;
            using ZeroAlloc.Serialisation;

            {{ns}}internal sealed class {{model.TypeName}}Serializer : ISerializer<{{model.FullTypeName}}>
            {
            {{suppressAttrs}}
                public void Serialize(IBufferWriter<byte> writer, {{model.FullTypeName}} value)
                {
                    {{serializerCall}}
                }

            {{suppressAttrs}}
                public {{model.FullTypeName}}? Deserialize(ReadOnlySpan<byte> buffer)
                {
                    if (buffer.IsEmpty) return default;
                    {{deserializeCall}}
                }
            }
            """;

        ctx.AddSource($"{model.TypeName}Serializer.g.cs", source);
    }
}
