using System;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Serialisation.Generator;

/// <summary>
/// Emits transparent serializers for <c>[ValueObject]</c>-decorated
/// single-property partial structs across the three supported backends
/// (System.Text.Json, MessagePack, MemoryPack). Each emission method is
/// gated by a check on the consuming compilation's assembly references —
/// adopters who don't reference a given backend package pay zero code-gen
/// for it.
/// </summary>
internal static class ValueObjectEmitter
{
    private const string SystemTextJsonBackendAssembly = "ZeroAlloc.Serialisation.SystemTextJson";
    private const string MessagePackBackendAssembly = "ZeroAlloc.Serialisation.MessagePack";
    private const string MemoryPackBackendAssembly = "ZeroAlloc.Serialisation.MemoryPack";

    internal static bool ReferencesSystemTextJson(Compilation compilation) =>
        ReferencesAssembly(compilation, SystemTextJsonBackendAssembly);

    internal static bool ReferencesMessagePack(Compilation compilation) =>
        ReferencesAssembly(compilation, MessagePackBackendAssembly);

    internal static bool ReferencesMemoryPack(Compilation compilation) =>
        ReferencesAssembly(compilation, MemoryPackBackendAssembly);

    private static bool ReferencesAssembly(Compilation compilation, string assemblyName) =>
        compilation.ReferencedAssemblyNames.Any(a =>
            string.Equals(a.Name, assemblyName, StringComparison.Ordinal));

    /// <summary>
    /// Emits a JsonConverter&lt;T&gt; for the value-object and a partial-struct
    /// extension carrying [JsonConverter(typeof(...))] so System.Text.Json picks
    /// it up automatically without explicit registration.
    /// </summary>
    internal static string EmitSystemTextJsonConverter(INamedTypeSymbol type, IPropertySymbol underlying)
    {
        var typeName = type.Name;
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        var typeKindKeyword = type.IsRecord ? "record struct" : "struct"; // V1 scope: structs only
        var readonlyKeyword = type.IsReadOnly ? "readonly " : "";
        var (readMethod, writeMethod) = SystemTextJsonReadWriteForType(underlying.Type);
        var converterName = $"{typeName}SystemTextJsonConverter";

        var nsOpen = string.IsNullOrEmpty(ns) ? "" : $"namespace {ns};\n\n";

        return $$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Text.Json;
            using System.Text.Json.Serialization;

            {{nsOpen}}[JsonConverter(typeof({{converterName}}))]
            public {{readonlyKeyword}}partial {{typeKindKeyword}} {{typeName}}
            {
            }

            internal sealed class {{converterName}} : JsonConverter<{{typeName}}>
            {
                public override {{typeName}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
                    => new {{typeName}}({{readMethod}});

                public override void Write(Utf8JsonWriter writer, {{typeName}} value, JsonSerializerOptions options)
                    => writer.{{writeMethod}}(value.{{underlying.Name}});
            }

            """;
    }

    /// <summary>
    /// Emits an IMessagePackFormatter&lt;T&gt; for the value-object plus a partial-struct
    /// extension carrying [MessagePackFormatter(typeof(...))] so MessagePack-CSharp's
    /// attribute-based resolver picks it up without explicit registration.
    /// </summary>
    internal static string EmitMessagePackFormatter(INamedTypeSymbol type, IPropertySymbol underlying)
    {
        var typeName = type.Name;
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        var typeKindKeyword = type.IsRecord ? "record struct" : "struct";
        var readonlyKeyword = type.IsReadOnly ? "readonly " : "";
        var (readMethod, _) = MessagePackReadWriteForType(underlying.Type);
        var formatterName = $"{typeName}MessagePackFormatter";

        var nsOpen = string.IsNullOrEmpty(ns) ? "" : $"namespace {ns};\n\n";

        return $$"""
            // <auto-generated/>
            #nullable enable

            using MessagePack;
            using MessagePack.Formatters;

            {{nsOpen}}[MessagePackFormatter(typeof({{formatterName}}))]
            public {{readonlyKeyword}}partial {{typeKindKeyword}} {{typeName}}
            {
            }

            internal sealed class {{formatterName}} : IMessagePackFormatter<{{typeName}}>
            {
                public void Serialize(ref MessagePackWriter writer, {{typeName}} value, MessagePackSerializerOptions options)
                    => writer.Write(value.{{underlying.Name}});

                public {{typeName}} Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
                    => new {{typeName}}({{readMethod}});
            }

            """;
    }

    private static (string ReadCall, string WriteArgFormat) MessagePackReadWriteForType(ITypeSymbol underlyingType)
    {
        return underlyingType.SpecialType switch
        {
            SpecialType.System_Int32   => ("reader.ReadInt32()",   "{0}"),
            SpecialType.System_Int64   => ("reader.ReadInt64()",   "{0}"),
            SpecialType.System_Int16   => ("reader.ReadInt16()",   "{0}"),
            SpecialType.System_Single  => ("reader.ReadSingle()",  "{0}"),
            SpecialType.System_Double  => ("reader.ReadDouble()",  "{0}"),
            SpecialType.System_Boolean => ("reader.ReadBoolean()", "{0}"),
            SpecialType.System_String  => ("reader.ReadString()!", "{0}"),
            _ => ("reader.ReadString()!", "{0}"),
        };
    }

    private static (string ReadCall, string WriteMethod) SystemTextJsonReadWriteForType(ITypeSymbol underlyingType)
    {
        return underlyingType.SpecialType switch
        {
            SpecialType.System_Int32   => ("reader.GetInt32()",   "WriteNumberValue"),
            SpecialType.System_Int64   => ("reader.GetInt64()",   "WriteNumberValue"),
            SpecialType.System_Int16   => ("reader.GetInt16()",   "WriteNumberValue"),
            SpecialType.System_Decimal => ("reader.GetDecimal()", "WriteNumberValue"),
            SpecialType.System_Double  => ("reader.GetDouble()",  "WriteNumberValue"),
            SpecialType.System_Single  => ("reader.GetSingle()",  "WriteNumberValue"),
            SpecialType.System_String  => ("reader.GetString()!", "WriteStringValue"),
            SpecialType.System_Boolean => ("reader.GetBoolean()", "WriteBooleanValue"),
            _ when string.Equals(underlyingType.ToDisplayString(), "System.Guid", StringComparison.Ordinal)
                => ("reader.GetGuid()", "WriteStringValue"),
            _ when string.Equals(underlyingType.ToDisplayString(), "System.DateTime", StringComparison.Ordinal)
                => ("reader.GetDateTime()", "WriteStringValue"),
            _ => ("reader.GetString()!", "WriteStringValue"), // fallback — let the compiler complain if the user's underlying type doesn't accept this
        };
    }
}
