using System;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Serialisation.Generator;

/// <summary>
/// Emits transparent serializers for <c>[ValueObject]</c>-decorated
/// single-property partial structs across the three supported backends
/// (System.Text.Json, MessagePack, MemoryPack). Each emission method is
/// gated by a check on the consuming compilation's assembly references —
/// adopters who don't reference a given backend package pay zero code-gen
/// for it.
/// </summary>
internal static class ValueObjectEmitter
{
    private const string SystemTextJsonBackendAssembly = "ZeroAlloc.Serialisation.SystemTextJson";
    private const string MessagePackBackendAssembly = "ZeroAlloc.Serialisation.MessagePack";
    private const string MemoryPackBackendAssembly = "ZeroAlloc.Serialisation.MemoryPack";

    internal static bool ReferencesSystemTextJson(Compilation compilation) =>
        ReferencesAssembly(compilation, SystemTextJsonBackendAssembly);

    internal static bool ReferencesMessagePack(Compilation compilation) =>
        ReferencesAssembly(compilation, MessagePackBackendAssembly);

    internal static bool ReferencesMemoryPack(Compilation compilation) =>
        ReferencesAssembly(compilation, MemoryPackBackendAssembly);

    private static bool ReferencesAssembly(Compilation compilation, string assemblyName) =>
        compilation.ReferencedAssemblyNames.Any(a =>
            string.Equals(a.Name, assemblyName, StringComparison.Ordinal));

    /// <summary>
    /// Emits a JsonConverter&lt;T&gt; for the value-object and a partial-struct
    /// extension carrying [JsonConverter(typeof(...))] so System.Text.Json picks
    /// it up automatically without explicit registration.
    /// </summary>
    internal static string EmitSystemTextJsonConverter(INamedTypeSymbol type, IPropertySymbol underlying)
    {
        var typeName = type.Name;
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        var typeKindKeyword = type.IsRecord ? "record struct" : "struct"; // V1 scope: structs only
        var readonlyKeyword = type.IsReadOnly ? "readonly " : "";
        var (readMethod, writeMethod) = SystemTextJsonReadWriteForType(underlying.Type);
        var converterName = $"{typeName}SystemTextJsonConverter";

        var nsOpen = string.IsNullOrEmpty(ns) ? "" : $"namespace {ns};\n\n";

        return $$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Text.Json;
            using System.Text.Json.Serialization;

            {{nsOpen}}[JsonConverter(typeof({{converterName}}))]
            public {{readonlyKeyword}}partial {{typeKindKeyword}} {{typeName}}
            {
            }

            internal sealed class {{converterName}} : JsonConverter<{{typeName}}>
            {
                public override {{typeName}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
                    => new {{typeName}}({{readMethod}});

                public override void Write(Utf8JsonWriter writer, {{typeName}} value, JsonSerializerOptions options)
                    => writer.{{writeMethod}}(value.{{underlying.Name}});
            }

            """;
    }

    /// <summary>
    /// Emits a single per-assembly public extension method that registers every
    /// generator-emitted [ValueObject] JsonConverter into a JsonSerializerOptions
    /// instance. Closes the JsonSerializerContext interop gap — STJ's source
    /// generator doesn't see [JsonConverter] attributes added by other generators,
    /// so consumers using a context-based pipeline need an explicit registration
    /// path. The extension lives in the ZeroAlloc.Serialisation.SystemTextJson
    /// namespace for discoverability via the using consumers already have.
    /// </summary>
    internal static string EmitSystemTextJsonRegistrar(
        System.Collections.Generic.IReadOnlyList<(INamedTypeSymbol Type, IPropertySymbol UnderlyingProperty)> valueObjects)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Serialisation.SystemTextJson;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registers every [ZeroAlloc.ValueObjects.ValueObject] partial struct's");
        sb.AppendLine("/// generator-emitted JsonConverter into a JsonSerializerOptions. Call this");
        sb.AppendLine("/// when using JsonSerializerContext (the source-generated typeinfo pipeline)");
        sb.AppendLine("/// — STJ resolves options.Converters before the context's typeinfo, so the");
        sb.AppendLine("/// underlying-primitive wire format takes precedence over default struct");
        sb.AppendLine("/// serialization.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class ValueObjectJsonConvertersExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::System.Text.Json.JsonSerializerOptions AddZeroAllocValueObjectConverters(this global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        foreach (var (type, _) in valueObjects)
        {
            var converterFqn = BuildConverterFqn(type);
            sb.AppendLine($"        options.Converters.Add(new {converterFqn}());");
        }
        sb.AppendLine("        options.TypeInfoResolverChain.Insert(0, global::ZeroAlloc.Serialisation.SystemTextJson.ValueObjectJsonTypeInfoResolver.Default);");
        sb.AppendLine("        return options;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits a single per-assembly internal IJsonTypeInfoResolver that returns
    /// pre-configured JsonTypeInfo&lt;T&gt; for every value-object in the
    /// assembly. Required for JsonSerializerContext consumers — the startup
    /// JsonPropertyInfo.Configure walk asks the resolver chain for typeinfo,
    /// and JsonContext's source-gen-emitted resolver doesn't have usable
    /// metadata for [ValueObject] types (Roslyn gens can't see the
    /// [JsonConverter] attribute the per-type emitter adds via a partial).
    /// </summary>
    internal static string EmitSystemTextJsonResolver(
        System.Collections.Generic.IReadOnlyList<(INamedTypeSymbol Type, IPropertySymbol UnderlyingProperty)> valueObjects)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Serialisation.SystemTextJson;");
        sb.AppendLine();
        sb.AppendLine("internal sealed class ValueObjectJsonTypeInfoResolver : global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver");
        sb.AppendLine("{");
        sb.AppendLine("    public static ValueObjectJsonTypeInfoResolver Default { get; } = new();");
        sb.AppendLine();
        sb.AppendLine("    public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        foreach (var (type, _) in valueObjects)
        {
            var typeFqn = BuildTypeFqn(type);
            var converterFqn = BuildConverterFqn(type);
            sb.AppendLine($"        if (type == typeof({typeFqn}))");
            sb.AppendLine($"            return global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<{typeFqn}>(options, new {converterFqn}());");
        }
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildTypeFqn(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        return string.IsNullOrEmpty(ns) ? $"global::{type.Name}" : $"global::{ns}.{type.Name}";
    }

    private static string BuildConverterFqn(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        var converterName = $"{type.Name}SystemTextJsonConverter";
        return string.IsNullOrEmpty(ns) ? $"global::{converterName}" : $"global::{ns}.{converterName}";
    }

    /// <summary>
    /// Emits an IMessagePackFormatter&lt;T&gt; for the value-object plus a partial-struct
    /// extension carrying [MessagePackFormatter(typeof(...))] so MessagePack-CSharp's
    /// attribute-based resolver picks it up without explicit registration.
    /// </summary>
    internal static string EmitMessagePackFormatter(INamedTypeSymbol type, IPropertySymbol underlying)
    {
        var typeName = type.Name;
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        var typeKindKeyword = type.IsRecord ? "record struct" : "struct";
        var readonlyKeyword = type.IsReadOnly ? "readonly " : "";
        var (readMethod, _) = MessagePackReadWriteForType(underlying.Type);
        var formatterName = $"{typeName}MessagePackFormatter";

        var nsOpen = string.IsNullOrEmpty(ns) ? "" : $"namespace {ns};\n\n";

        return $$"""
            // <auto-generated/>
            #nullable enable

            using MessagePack;
            using MessagePack.Formatters;

            {{nsOpen}}[MessagePackFormatter(typeof({{formatterName}}))]
            public {{readonlyKeyword}}partial {{typeKindKeyword}} {{typeName}}
            {
            }

            internal sealed class {{formatterName}} : IMessagePackFormatter<{{typeName}}>
            {
                public void Serialize(ref MessagePackWriter writer, {{typeName}} value, MessagePackSerializerOptions options)
                    => writer.Write(value.{{underlying.Name}});

                public {{typeName}} Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
                    => new {{typeName}}({{readMethod}});
            }

            """;
    }

    /// <summary>
    /// Emits a single per-assembly file containing both an internal
    /// IFormatterResolver listing every value-object's formatter AND a public
    /// extension method AddZeroAllocValueObjectFormatters that prepends the
    /// resolver to a MessagePackSerializerOptions chain. Required for
    /// MessagePack.SourceGenerator (AOT) consumers — the AOT-generated resolver
    /// doesn't have usable typeinfo for [ValueObject] types because Roslyn gens
    /// can't see the [MessagePackFormatter] attribute our per-type emitter adds
    /// via a partial-struct extension. Single file (unlike STJ's split) because
    /// MessagePack has only one registration shape — the resolver chain.
    /// </summary>
    internal static string EmitMessagePackResolver(
        System.Collections.Generic.IReadOnlyList<(INamedTypeSymbol Type, IPropertySymbol UnderlyingProperty)> valueObjects)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Serialisation.MessagePack;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Resolves IMessagePackFormatter&lt;T&gt; for every [ZeroAlloc.ValueObjects.ValueObject]");
        sb.AppendLine("/// partial struct in this assembly. Prepend via AddZeroAllocValueObjectFormatters.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed class ValueObjectMessagePackResolver : global::MessagePack.IFormatterResolver");
        sb.AppendLine("{");
        sb.AppendLine("    public static ValueObjectMessagePackResolver Default { get; } = new();");
        sb.AppendLine();
        sb.AppendLine("    public global::MessagePack.Formatters.IMessagePackFormatter<T>? GetFormatter<T>()");
        sb.AppendLine("        => FormatterCache<T>.Formatter;");
        sb.AppendLine();
        sb.AppendLine("    private static class FormatterCache<T>");
        sb.AppendLine("    {");
        sb.AppendLine("        public static readonly global::MessagePack.Formatters.IMessagePackFormatter<T>? Formatter");
        sb.AppendLine("            = (global::MessagePack.Formatters.IMessagePackFormatter<T>?)GetFormatterUntyped(typeof(T));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static object? GetFormatterUntyped(global::System.Type type)");
        sb.AppendLine("    {");
        foreach (var (type, _) in valueObjects)
        {
            var typeFqn = BuildTypeFqn(type);
            var formatterFqn = BuildFormatterFqn(type);
            sb.AppendLine($"        if (type == typeof({typeFqn}))");
            sb.AppendLine($"            return new {formatterFqn}();");
        }
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registers every [ZeroAlloc.ValueObjects.ValueObject] partial struct's");
        sb.AppendLine("/// generator-emitted IMessagePackFormatter by prepending ValueObjectMessagePackResolver");
        sb.AppendLine("/// to a MessagePackSerializerOptions resolver chain. Call this AFTER setting your");
        sb.AppendLine("/// primary resolver (e.g. GeneratedMessagePackResolver.Instance) — call order");
        sb.AppendLine("/// matters; this method assumes the caller's options.Resolver is the fallback.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class ValueObjectMessagePackFormattersExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::MessagePack.MessagePackSerializerOptions AddZeroAllocValueObjectFormatters(this global::MessagePack.MessagePackSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var composite = global::MessagePack.Resolvers.CompositeResolver.Create(");
        sb.AppendLine("            ValueObjectMessagePackResolver.Default,");
        sb.AppendLine("            options.Resolver);");
        sb.AppendLine("        return options.WithResolver(composite);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildFormatterFqn(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        var formatterName = $"{type.Name}MessagePackFormatter";
        return string.IsNullOrEmpty(ns) ? $"global::{formatterName}" : $"global::{ns}.{formatterName}";
    }

    /// <summary>
    /// Emits a MemoryPackFormatter&lt;T&gt; for the value-object plus a module
    /// initializer that registers it with <c>MemoryPackFormatterProvider</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Deviation from the plan: the plan called for
    /// <c>[MemoryPackable(GenerateType.NoGenerate)] [MemoryPackCustomFormatter&lt;TFormatter, T&gt;]</c>
    /// on the partial struct. Reality (MemoryPack 1.21.x):
    /// <list type="bullet">
    /// <item><c>MemoryPackCustomFormatterAttribute&lt;TFormatter, T&gt;</c> is abstract
    ///   AND its <c>AttributeUsage</c> only targets properties + fields — it cannot be
    ///   applied to a type, and even if it could, the consumer would have to derive a
    ///   concrete subclass that overrides <c>GetFormatter()</c>.</item>
    /// <item>The canonical pattern for "I have a hand-rolled formatter for type T" is
    ///   <c>MemoryPackFormatterProvider.Register&lt;T&gt;(formatter)</c> at startup —
    ///   which we automate via a <c>[ModuleInitializer]</c>.</item>
    /// </list>
    /// No attribute is needed on the value-object struct itself; absence of
    /// <c>[MemoryPackable]</c> means MemoryPack's source generator generates nothing
    /// for the type, and the provider lookup at serialize-time finds our registered
    /// formatter instead.
    /// </para>
    /// </remarks>
    internal static string EmitMemoryPackFormatter(INamedTypeSymbol type, IPropertySymbol underlying)
    {
        var typeName = type.Name;
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        var underlyingFqn = underlying.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var formatterName = $"{typeName}MemoryPackFormatter";
        var registrarName = $"{typeName}MemoryPackFormatterRegistrar";

        var nsOpen = string.IsNullOrEmpty(ns) ? "" : $"namespace {ns};\n\n";

        return $$"""
            // <auto-generated/>
            #nullable enable

            using System.Runtime.CompilerServices;
            using MemoryPack;

            {{nsOpen}}internal static class {{registrarName}}
            {
                [ModuleInitializer]
                internal static void Register()
                {
                    if (!MemoryPackFormatterProvider.IsRegistered<{{typeName}}>())
                    {
                        MemoryPackFormatterProvider.Register<{{typeName}}>(new {{formatterName}}());
                    }
                }
            }

            internal sealed class {{formatterName}} : MemoryPackFormatter<{{typeName}}>
            {
                public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, scoped ref {{typeName}} value)
                    => writer.WriteValue<{{underlyingFqn}}>(value.{{underlying.Name}});

                public override void Deserialize(ref MemoryPackReader reader, scoped ref {{typeName}} value)
                    => value = new {{typeName}}(reader.ReadValue<{{underlyingFqn}}>()!);
            }

            """;
    }

    private static (string ReadCall, string WriteArgFormat) MessagePackReadWriteForType(ITypeSymbol underlyingType)
    {
        return underlyingType.SpecialType switch
        {
            SpecialType.System_Int32   => ("reader.ReadInt32()",   "{0}"),
            SpecialType.System_Int64   => ("reader.ReadInt64()",   "{0}"),
            SpecialType.System_Int16   => ("reader.ReadInt16()",   "{0}"),
            SpecialType.System_Single  => ("reader.ReadSingle()",  "{0}"),
            SpecialType.System_Double  => ("reader.ReadDouble()",  "{0}"),
            SpecialType.System_Boolean => ("reader.ReadBoolean()", "{0}"),
            SpecialType.System_String  => ("reader.ReadString()!", "{0}"),
            _ => ("reader.ReadString()!", "{0}"),
        };
    }

    private static (string ReadCall, string WriteMethod) SystemTextJsonReadWriteForType(ITypeSymbol underlyingType)
    {
        return underlyingType.SpecialType switch
        {
            SpecialType.System_Int32   => ("reader.GetInt32()",   "WriteNumberValue"),
            SpecialType.System_Int64   => ("reader.GetInt64()",   "WriteNumberValue"),
            SpecialType.System_Int16   => ("reader.GetInt16()",   "WriteNumberValue"),
            SpecialType.System_Decimal => ("reader.GetDecimal()", "WriteNumberValue"),
            SpecialType.System_Double  => ("reader.GetDouble()",  "WriteNumberValue"),
            SpecialType.System_Single  => ("reader.GetSingle()",  "WriteNumberValue"),
            SpecialType.System_String  => ("reader.GetString()!", "WriteStringValue"),
            SpecialType.System_Boolean => ("reader.GetBoolean()", "WriteBooleanValue"),
            _ when string.Equals(underlyingType.ToDisplayString(), "System.Guid", StringComparison.Ordinal)
                => ("reader.GetGuid()", "WriteStringValue"),
            _ when string.Equals(underlyingType.ToDisplayString(), "System.DateTime", StringComparison.Ordinal)
                => ("reader.GetDateTime()", "WriteStringValue"),
            _ => ("reader.GetString()!", "WriteStringValue"), // fallback — let the compiler complain if the user's underlying type doesn't accept this
        };
    }
}
